export const fikrLang = {
  uz: {
    title: 'O’quvchilarimiz fikri',
    o1n: 'Dev',
    o1u: 'developer_999',
    o1f: 'Tajribali mutaxassis bilan Islom an’analariga asoslangan psixologik ilmlarga ega bo‘ling! shoshiling!',
    o2n: 'Nigora',
    o2u: 'nigora_2003',
    o2f: 'kurs ruhiy salomatlik mutaxassislari psixoterapevt, psixiatr, nevrolog, psixolog) hamda ruhiy tarbiya mutaxasislari islomshunos, dinshunos, imom, otinoyi) uchun mo‘ljallangan. Bakalavriat, magistratura',
    o3n: 'Akmal',
    o3u: 'akmaljondev',
    o3f: 'Tajribali mutaxassis bilan Islom an’analariga asoslangan psixologik ilmlarga ega bo‘ling! shoshiling!',
    o4n: 'Bonu',
    o4u: 'Bonuchka_cha',
    o4f: 'kurs ruhiy salomatlik mutaxassislari psixoterapevt, psixiatr, nevrolog, psixolog) hamda ruhiy tarbiya mutaxasislari islomshunos, dinshunos, imom, otinoyi) uchun mo‘ljallanga',
  },
  kr: {
    title: '독자의 의견',
    o1n: '데브',
    o1u: '개발자 _999',
    o1f: '경험 많은 전문가와 함께 이슬람 전통을 기반으로 한 심리 과학을 즐기십시오! 서둘러!',
    o2n: '니고라',
    o2u: '니고라 _2003',
    o2f: '이 과정은 정신 건강 전문가(심리 치료사,정신과 의사,신경과 전문의,심리학자)와 정신 교육 전문가(이슬람 학자,신학자,이맘,오티노이)를 위해 고안되었습니다. 학부,대학원',
    o3n: '아크말',
    o3u: '아크말데브',
    o3f: '경험 많은 전문가와 함께 이슬람 전통을 기반으로 한 심리 과학을 즐기십시오! 서둘러!',
    o4n: '보누',
    o4u: '보누치카 _차',
    o4f: '이 과정은 정신 건강 전문가(심리 치료사,정신과 의사,신경과 전문의,심리학자)와 정신 교육 전문가(이슬람 학자,신학자,이맘,오티노이)를 위해 고안되었습니다.',
  },
};
