export const settingLang = {
  uz: {
    t1: 'Profil Sozlamalari',
    t2: 'Xafsizlik',
    imgS: 'Sizning sur’atingiz',
    imgT: 'Rasmni o’zgartirish jpg yoki png',
    del: 'O’chirish',
    ok: 'Tasdiqlash',
    secretS: 'Shaxsiy ma’lumotlar',
    secretT: 'Shaxsiy ma’lumotlaringizni o’zgartirishingiz mumkin.',
    p1: 'Ism',
    p2: 'Familiya',
    p3: 'E-Mail',
    p4: 'Telefon raqamni o’zgartirish',
    p5: 'Hozirgi telefon raqamingiz +99899 000-00-00',
    p6: 'Yangi telefon raqamni kiritish',
    p7: 'Parolni o’zgartirish',
    p8: 'Xavfsizlik tomonidan parolingizni yangilang.',
    p9: 'Avvalgi parol',
    p10: 'Yangi parolni kiritish',
    p11: 'Yangi parolni takrorlash',
    p12: 'Sms kodni kiriting',
    p13: 'ushbu raqamga kod yuborildi',
    p14: 'Sms kod muvaffaqiyatli tasdiqlandi',
    okey: 'OK',
  },
  kr: {
    t1: '프로필 설정',
    t2: '좌절',
    imgS: '당신의 속도',
    imgT: '이미지 변경',
    del: '삭제',
    ok: '배정',
    secretS: '개인 데이터',
    secretT: '개인 정보를 변경할 수 있습니다.',
    p1: '이름',
    p2: '성명',
    p3: '이메일',
    p4: '전화 번호 변경',
    p5: '현재 전화 번호는+99899 000-00-00 입니다',
    p6: '새 전화 번호 입력',
    p7: '비밀번호 변경',
    p8: '보안에 의해 암호를 업데이트합니다.',
    p9: '이전 비밀번호',
    p10: '새 암호 입력',
    p11: '새 암호를 반복합니다',
    p12: '문자 코드 입력',
    p13: '이 번호로 코드가 전송되었습니다',
    p14: '문자 코드가 성공적으로 확인되었습니다.',
    okey: '확인',
  },
};
