export const authLang = {
  uz: {
    kirish: 'Kirish',
    biz: 'Bizga qo’shiling!',
    registr: 'Ro’yxatdan o’tish',
    tel: 'Telefon raqamingiz',
    pas: 'Password',
    reset: 'Parolni unutdingizmi?',
    ok: 'Tasdiqlash',
    code: 'ga yuborilgan maxfiy kodni kiriting.',
    sendCode: 'Kodni kiriting',
    resetCode: 'Kodni qayta yuborish.',
    tikla: 'Parolni tiklash',
    t1: 'Yangi parolni tiklang va doimgidek saytimizdan foydalaning',
    t2: 'Yangi parol',
    t3: 'Yangi parolni takrorlang',
    t4: 'Parolni kitirish',
    t5: ' Parolni unutgan bo’lsangiz telefon raqamingiz orqali tiklashingiz mumkun',
    t6: 'Profile',
    t7: 'Ma’lumotingizni kiriting.',
    t8: 'JPG yoki PNG formatdagi sur’atingizni joylang.',
    t9: 'Rasm joylash',
    ism: 'Ismingiz',
    last: 'Familiyangiz',
    t10: 'Ro’yxatdan o’tish',
    t11: 'Yangi parol',
    t12: 'Yangi parolni takrorlang',
  },
  kr: {
    kirish: '소개',
    biz: '우리와 함께!',
    registr: '등록',
    tel: '전화 번호',
    pas: '비밀번호',
    reset: '비밀번호를 잊으셨나요?',
    ok: '배정',
    code: '보낸 비밀 코드를 입력.',
    sendCode: '코드 입력',
    resetCode: '코드를 다시 보냅니다.',
    tikla: '비밀번호 복구',
    t1: '새 암호를 재설정하고 언제나처럼 우리의 사이트를 사용',
    t2: '새 암호',
    t3: '새 암호를 반복합니다',
    t4: '비밀번호 키잉',
    t5: ' 비밀번호를 잊어 버린 경우 전화 번호를 통해 복구 할 수 있습니다',
    t6: '프로필',
    t7: '귀하의 정보를 입력.',
    t8: '페이스 북 또는 페이스 북 형식으로 페이스를 배치하십시오.',
    t9: '이미지 위치',
    ism: '당신의 이름',
    last: '당신의 성',
    t10: '등록',
    t11: '새 암호',
    t12: '새 암호를 반복합니다',
  },
};
